version: "3.8"

services:
  todo_app:
    build: .
    container_name: todo_fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/app
      - ./logs:/var/log/todo_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    user: "10001"
    ports:
      - "3100:3100"
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/wal:/wal
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/var/log/todo_app
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

volumes:
  postgres_data: {}
  grafana_data: {}

