"""Сделал колонку важности nullable

Revision ID: 40a466ab6362
Revises: cae6948ab5f6
Create Date: 2025-03-23 20:59:48.614157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a466ab6362'
down_revision: Union[str, None] = 'cae6948ab5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('importance', sa.Enum('important', 'very_important', 'not_important', name='taskimportance'), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='taskstatus'),
               nullable=True)
    op.drop_column('tasks', 'nice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('nice', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='taskstatus'),
               nullable=False)
    op.drop_column('tasks', 'importance')
    # ### end Alembic commands ###
