"""Добавил поле приятно

Revision ID: cae6948ab5f6
Revises: eb7878258035
Create Date: 2025-01-29 21:26:01.323198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae6948ab5f6'
down_revision: Union[str, None] = 'eb7878258035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'nice',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'nice',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
